question_data = [
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "text": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "text": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "text": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
     "answer": "False", "incorrect_answers": ["True"]}

]
